Ror/config/routes.rb
UploadPhoto::Application.routes.draw do

  namespace :rest do
    resources :photos, only: [:create]
    resources :statistics, only: [:show]
  end

  resources :statistics, only: [:index, :show]

  root :to => 'statistics#index'

end

Ror/app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :s3_photo, :fs_photo, :fs_s3_photo, :origin_size, :origin_height, :origin_width

  has_one :statistics

  MAIN_RETINA = 'main_retina'
  MAIN_MEDIUM = 'main_medium'
  THUMB_RETINA = 'thumb_retina'
  THUMB_MEDIUM = 'thumb_medium'

  mount_uploader :s3_photo, S3PhotoUploader
  mount_uploader :fs_photo, FsPhotoUploader
  mount_uploader :fs_s3_photo, S3PhotoUploader
end

Ror/app/models/statistics.rb
class Statistics < ActiveRecord::Base
  attr_accessible :photo, :photo_id, :s3_photo_stats, :fs_photo_stats, :fs_s3_photo_stats

  belongs_to :photo
end

Ror/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery
end

Ror/app/controllers/rest/photos_controller.rb
class Rest::PhotosController < ApplicationController

  UPLOAD_TYPE_FS = 'fs'
  UPLOAD_TYPE_S3 = 's3'

  def create
    @photo = Photo.new()

    if params[:photo].present? && params[:upload_type].present?
      if params[:upload_type] == UPLOAD_TYPE_FS
        @photo.fs_photo = params[:photo]
        @photo.size = params[:photo].size
        @photo.filename = params[:photo].original_filename
        if fs_photo_save(@photo)
          Stalker.enqueue('uploader.create_fs_s3_photo_from_fs_photo', [@photo.id])
          return_status_ok(@photo.id)
        else
          return_status_fail
        end
      else
        @photo.s3_photo = params[:photo]
        @photo.size = params[:photo].size
        @photo.filename = params[:photo].original_filename
        if s3_photo_save(@photo)
          return_status_ok(@photo.id)
        else
          return_status_fail
        end
      end
    else
      return_status_fail
    end
  end


  private


  def return_status_ok(id)
    respond_to do |format|
      format.json { render json: { status: "ok", id: id } }
    end
    return false
  end

  def return_status_fail
    respond_to do |format|
      format.json { render json: { status: "fail" } }
    end
    return false
  end

  def fs_photo_save(photo)
    save_time = Benchmark.realtime { photo.save }
    Statistics.create( photo: photo, fs_photo_stats: save_time )
  end

  def s3_photo_save(photo)
    save_time = Benchmark.realtime { photo.save }
    Statistics.create( photo: photo, s3_photo_stats: save_time )
  end

end

Ror/app/controllers/rest/statistics_controller.rb
class Rest::StatisticsController < ApplicationController

  def show
    @photo = Photo.find_by_id( params[:id] )

    unless @photo.nil?
      s3_time = ''
      fs_time = ''
      fs_s3_time = ''

      unless @photo.statistics.nil?
        s3_time = @photo.statistics.s3_photo_stats.to_s
        fs_time = @photo.statistics.fs_photo_stats.to_s
        fs_s3_time = @photo.statistics.fs_s3_photo_stats.to_s
      end

      if !s3_time.blank?
        respond_to do |format|
          format.json { render json: { status: "ok", type: Rest::PhotosController::UPLOAD_TYPE_S3, s3_time: s3_time } }
        end
      elsif !fs_time.blank? && !fs_s3_time.blank?
        respond_to do |format|
          format.json { render json: { status: "ok", type: Rest::PhotosController::UPLOAD_TYPE_FS, fs_time: fs_time, fs_s3_time: fs_s3_time } }
        end
      else
        respond_to do |format|
          format.json { render json: { status: "fail" } }
        end
      end

    else
      respond_to do |format|
        format.json { render json: { status: "fail" } }
      end
    end

  end

end

Ror/app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController

  def index
    @photos = Photo.page(params[:page] || 1).per(50)
  end

  def show
    @photo = Photo.find_by_id(params[:id])
  end

end

Ror/app/helpers/application_helper.rb
module ApplicationHelper
end

Ror/app/helpers/rest/photos_helper.rb
module Rest::PhotosHelper
end

Ror/app/helpers/rest/statistics_helper.rb
module Rest::StatisticsHelper
end

Ror/app/helpers/statistics_helper.rb
module StatisticsHelper

  def photo_size(photo)
    if !photo.size.blank?
      "#{photo.size} kb"
    else
      "0 kb"
    end
  end

  def photo_filename(photo)
    if !photo.filename.blank?
      "Photo - #{photo.filename} - details"
    else
      "No Photo"
    end
  end

  def photo_original(photo)
    if !photo.s3_photo.path.blank?
      image_tag(photo.s3_photo.url, style: "width:700px !important")
    elsif !photo.fs_s3_photo.path.blank?
      image_tag(photo.fs_s3_photo.url, style: "width:700px !important")
    else
      image_tag("default.jpg", style: "width:80px !important")
    end
  end

  def photo_version(photo, version)
    width = 700
    case version
    when Photo::MAIN_RETINA
      width = 640
    when Photo::MAIN_MEDIUM
      width = 320
    when Photo::THUMB_RETINA
      width = 160
    when Photo::THUMB_MEDIUM
      width = 80
    end

    if !photo.s3_photo.path.blank?
      image_tag(photo.s3_photo.url(version), style: "width:#{width}px !important")
    elsif !photo.fs_s3_photo.path.blank?
      image_tag(photo.fs_s3_photo.url(version), style: "width:#{width}px !important")
    else
      image_tag("default.jpg", style: "width:80px !important")
    end
  end

end

Ror/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UploadPhoto</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="header">
    <%= yield :title_page %>&nbsp;
  </div>

  <div id="main">
    <%= yield %>
  </div>

  <div class="clear"></div>


</body>
</html>

Ror/app/views/statistics/_photo.html.erb
<tr valign="top" class="<%= cycle('even','odd') %>" id="<%= photo.id %>">

  <td>
    <%= photo_version( photo, Photo::THUMB_MEDIUM ) %>
  </td>

  <td>
    <%= photo.statistics && !photo.statistics.s3_photo_stats.blank? ? "#{photo.statistics.s3_photo_stats.to_s} s" : "-" %>
  </td>

  <td>
    <%= photo.statistics && !photo.statistics.fs_photo_stats.blank? ? "#{photo.statistics.fs_photo_stats.to_s} s" : "-" %>
  </td>

  <td>
    <%= photo.statistics && !photo.statistics.fs_s3_photo_stats.blank? ? "#{photo.statistics.fs_s3_photo_stats.to_s} s" : "-" %>
  </td>

  <td>
    <%= photo_size(photo) %>
  </td>

  <td>
    <%= link_to "Details", statistic_path(photo), class: "text-link" %>
  </td>

</tr>

Ror/app/views/statistics/index.html.erb
<% content_for :title_page do  %>
  <h2>Statistics</h2>
<% end %>

<% if @photos.empty? %>
  <table width="100%" border="0" cellspacing="0" cellpadding="0" id="table">
    <tr class="title" valign="top">
      <td class="col_1" style='text-align:center'>No information found</td>
    </tr>
  </table>
<% else %>
  <table width="100%" border="0" cellspacing="0" cellpadding="0" id="table">
    <tr class="title" valign="top">
      <td>Photo</td>
      <td>S3<br />download<br />time</td>
      <td>FS<br />download<br />time</td>
      <td>FS to S3<br />download<br />time</td>
      <td>Original<br />File<br />Size</td>
      <td>Revise</td>
    </tr>
    <%= render partial: "photo", collection: @photos %>
  </table>

  <%= paginate @photos %>
<% end %>

Ror/app/views/statistics/show.html.erb
<% content_for :title_page do  %>
  <h2><%= photo_filename(@photo) %></h2>
<% end %>


<div class="content" style="display:block;">

  <label>Photo in original size:</label>
  <span class='text-form'><%= photo_original(@photo) %></span><br />

  <label>Photo 640x640:</label>
  <span class='text-form'><%= photo_version( @photo, Photo::MAIN_RETINA ) %></span><br />

  <label>Photo 320x320:</label>
  <span class='text-form'><%= photo_version( @photo, Photo::MAIN_MEDIUM ) %></span><br />

  <label>Photo 160x160:</label>
  <span class='text-form'><%= photo_version( @photo, Photo::THUMB_RETINA ) %></span><br />

  <label>Photo 80x80:</label>
  <span class='text-form'><%= photo_version( @photo, Photo::THUMB_MEDIUM ) %></span><br />

  <label>S3 download time:</label>
  <span class='text-form'><%= @photo.statistics && !@photo.statistics.s3_photo_stats.blank? ? "#{@photo.statistics.s3_photo_stats.to_s} s" : "-" %></span><br />

  <label>FS download time:</label>
  <span class='text-form'><%= @photo.statistics && !@photo.statistics.fs_photo_stats.blank? ? "#{@photo.statistics.fs_photo_stats.to_s} s" : "-" %></span><br />

  <label>FS to S3 download time:</label>
  <span class='text-form'><%= @photo.statistics && !@photo.statistics.fs_s3_photo_stats.blank? ? "#{@photo.statistics.fs_s3_photo_stats.to_s} s" : "-" %></span><br />

  <label>Original File Size:</label>
  <span class='text-form'><%= photo_size(@photo) %></span><br />

</div>

<div class="actionbar">
  <%= link_to "Back", statistics_path, class: 'btn' %>
</div>